append_unmatched: true
flatten_single_child_sections: true
nav:
  - Home: index.md
  - Product Briefs:
      - Template: product-brief-template.md
      - Integration Hub: integration-hub.md
  - Blog:
    - blog/index.md